### ISSUE TITLE
No routes are shown by the app

### ISSUE THREAD

**Issue by jinankjain** [Greennav/webapp#23]
I tried to build the project as given in the instructions. Build was successful but when I access website it just show a map and form and form does not get submit and does not show any results.

**Comment by fabianbormann** [comment]
Hi @jinankjain  do you use google chrome? Can you post a screenshot or error log message?

**Comment by jinankjain** [comment]
![error](https://cloud.githubusercontent.com/assets/3854904/13523683/e77defa6-e21c-11e5-899f-a85216e4f8f6.png)

**Comment by jinankjain** [comment]
@fabianbormann yes I am using google chrome

**Comment by maxlorenz** [comment]
Hi @jinankjain 
The server doesn't interact with the sent data but sends a static json response (mockup). Which command did you use for polyserve?

**Comment by jinankjain** [comment]
@maxlorenz I am using polyserve -p 8000

**Comment by jinankjain** [comment]
@maxlorenz @fabianbormann I did git pull and bower update also then also I am unable to obtain any output

**Comment by maxlorenz** [comment]
Can you open localhost:6833?

**Comment by jinankjain** [comment]
@maxlorenz  No that page does not open up.

**Comment by jinankjain** [comment]
@maxlorenz @fabianbormann Finally it worked for me thanks for the help.

Now could you please tell me some easy bugs to fix so that I could get familiarize with the code base.

**Comment by fabianbormann** [comment]
Hi @jinankjain,  :+1:  what was your solution?
You could improve the docs https://github.com/Greennav/greennav.github.io/issues if you want to get familiar with the code. If you post the solution of your problem I will close this issue. Thanks!

**Comment by jinankjain** [comment]
@fabianbormann I just forgot to update i.e git pull the service-routing, I saw you updated that also and after pulling the updated version of that it got fixed.

Thanks, once again
