### ISSUE TITLE
Issue with GoogleMap

### ISSUE THREAD

**Issue by jinankjain** [Greennav/webapp#31]
Steps to reproduce the error:
In index.html in gn-map change map-type from OpenStreetMap to GoogleMap

![screenshot from 2016-03-15 17 57 05](https://cloud.githubusercontent.com/assets/3854904/13777734/d7674c34-ead7-11e5-9047-6406cb11bd47.png)

**Comment by maxlorenz** [comment]
Could you please also post the console log from Chrome?

**Comment by jinankjain** [comment]
![screenshot from 2016-03-15 19 00 30](https://cloud.githubusercontent.com/assets/3854904/13779294/4a4a0838-eae0-11e5-9f66-8bb035d9652c.png)

**Comment by jinankjain** [comment]
These are usual error, I have those error in gn-map but there it worked fine Google Map were loading

**Comment by luviiit** [comment]
@jinankjain, the google maps are actually getting loaded but they are hidden behind the white screen. When you remove all the elements except `gn-map` in index.html you can see the google maps. I wonder why is this not happening with osm.

**Comment by fabianbormann** [comment]
@luviiit I've just closed the issue with my commit. The problem was that the height of ```google-map``` was "0 px". I had to force it to "100 vh" in the css. In my ```osm-map``` element I had already set #map container height to 100%.

https://github.com/GoogleWebComponents/google-map/blob/master/google-map.html#L63
https://github.com/fabianbormann/osm-map/blob/master/osm-map.html#L24

**Comment by jinankjain** [comment]
Yes that fixed the issue.

**Comment by luviiit** [comment]
Apparently, wrapping the `gn-map` element with some other element hides google map display.

`<gn-map map-type="GoogleMap"></gn-map>` works

but 

`<div><gn-map map-type="GoogleMap"></gn-map></div>` does not work.

**Comment by luviiit** [comment]
@fabianbormann changing the size to 100vh is overflowing the page. May be we can change it to 90vh for now and then later change it such that it automatically fits the remaining screen.

**Comment by fabianbormann** [comment]
Hey @luviiit, 

sry I didn't saw that :flushed: ! Thank's for that hint! 
But 90vh is a kind of magic number ;) don't know if it's the best solution for all devices.. 

I solved it using css calc function (100vh - toolbar height).  https://github.com/Greennav/webapp/blob/master/css/style.css#L12

Cheers,
Fabian

**Comment by jinankjain** [comment]
@fabianbormann One more fix could be instead of using class="flex" we could use class="content fit"

I guess that would also work :)

**Comment by fabianbormann** [comment]
@jinankjain can you upload an working example, because for me setting class to ```content fit``` and remove the css line does not work? 

In the new iron-flex-layout-classes.html I found ```.fit``` but not ```.content``` 
https://github.com/PolymerElements/iron-flex-layout/blob/master/iron-flex-layout-classes.html#L380

**Comment by jinankjain** [comment]
#37
