### ISSUE TITLE
Logo Suggestion

### ISSUE THREAD

**Issue by luviiit** [Greennav/webapp#35]
I roughly thought of a design for logo.

![screenshot from 2016-03-16 06 18 49](https://cloud.githubusercontent.com/assets/7158765/13798777/70767776-eb3f-11e5-9c9b-f7e2a0f48bd5.png)
......
![screenshot from 2016-03-16 06 28 59](https://cloud.githubusercontent.com/assets/7158765/13798909/96ad427a-eb40-11e5-8074-a586dd0a3069.png)

Any suggestions/criticisms are welcome.

**Comment by luviiit** [comment]
I have some other rough designs in mind too. All are around terms `navigation` and `efficiency`.

**Comment by fabianbormann** [comment]
Hey @luviiit,

the logo design will be a part of a GSoC project (corporate design). Please add your logo ideas to your proposal if you want to apply for GSoC. If you only want to share logo ideas with us or with the community please use the G+ page or google groups. 

Thanks a lot!
