### ISSUE TITLE
Grammatical error and no need for JSON.stringify(mapType)

### ISSUE THREAD

**Issue by tahteche** [Greennav/webapp#40]
In the first <p> tag within the template element:

1.  "selected" is spelled as "Seledcted"
2. JSON.stringify(mapType) is called within the mustache (`{{JSON.stringify(mapType)}}`) instead of just `{{mapType}}`

I don't think the <p> tag is needed at all but guess its for correction purposes.

**Comment by tahteche** [comment]
I am working on this.

**Comment by fabianbormann** [comment]
It's just a redundant line nothing to fix here.. Removed the line in 294f8dd
