### ISSUE TITLE
Discussion about User Notifications

### ISSUE THREAD

**Issue by luviiit** [Greennav/webapp#42]
Hi, I this issue is for the discussions about User Notifications. It would be great if we could create a `gn-notification` element which has enough flexibility and features to incorporate all type of notifications. So that we can just use `gn-notification` tag with suitable attribute values (like color, size, position, animation, message content, etc) to generate a notification for all our needs.

I could think of the following reasons for which notification would pop up:

1. To inform about critical battery levels, critical battery life
2. Traffic
3. To inform about a new feature in GreenNav
4. May be some map changes relevant to the user like a new shorter route from one place to another

Please correct if I am wrong.
@fabianbormann, should I give it a try by creating a new `gn-notification` element and writing code for it?
Is there anything that you would like to tell about Notifications, how should I proceed it, any special features?

Any other suggestions?
Also is it okay to discuss these things here (in github issues) and now or wait for GSoC period to start?

**Comment by fabianbormann** [comment]
Hey @luviiit great idea! I think notifications could implement besides GSoC because there are so much ideas and todos during GSoC that a ```gn-notification``` element is not a "anticipation" .. So yes sure! :blush:  I will create an empty repository that you could fork and implement the basics (use the polymer seed element). Maybe you could implement different dialog types and notifications using ```paper-toast``` and ```paper-dialog```.

**Comment by fabianbormann** [comment]
GLHF :+1: https://github.com/Greennav/gn-notification

**Comment by luviiit** [comment]
Thank you very much @fabianbormann :smiley:
Also should I make issues for discussing about logging, coding style guide and documentation because I have to know/discuss about them as I would be writing those in my GSoC proposal.

**Comment by fabianbormann** [comment]
yes - create those issues in the related repo (docs = greennav.github.io) :blush:
