### ISSUE TITLE
Bot for doing automatic changes

### ISSUE THREAD

**Issue by luviiit** [Greennav/webapp#45]
Hey, I am thinking of writing a bot for making some automatic updates like README.md upon change of doc strings in source code, CONTRIBUTORS.md when there are some new contributors, etc. For some more details - [gn-api #6](https://github.com/Greennav/gn-api/issues/6#issuecomment-202116594)

@fabianbormann, should I go on? If yes, then please make a repo where the Bot code would go and a github bot account whose personal access token would be used to push the changes.

**Comment by luviiit** [comment]
Also, in what language should we write it? Python?

**Comment by fabianbormann** [comment]
Hey @luviiit what would be the advantage over exisitng polymer solutions? https://www.polymer-project.org/1.0/docs/start/reusableelements.html#documentation

**Comment by luviiit** [comment]
@fabianbormann, the docs of the element are shown at `localhost:8080/components/test-element/` but there is no polymer solution which generates the docs and put them in README.md which is displayed at the github page of the element. If we don't have a bot then we have to manually update README.md everytime there is any change in doc strings of source code.
Did I make it clear?

**Comment by luviiit** [comment]
Just for clarity, I would be using [hydrolysis](https://github.com/Polymer/hydrolysis) to extract the docs. It can be done in 3-4 lines of simple code.

**Comment by jinankjain** [comment]
@luviiit Why don't we go for the solution using gh-pages that are generated by polymer?

**Comment by jinankjain** [comment]
@luviiit @fabianbormann  I have created a sample gh-pages for gn-api that is having documentation for all the properties and member function http://jinankjain.github.io/gn-api/components/gn-api/

**Comment by jinankjain** [comment]
@luviiit @fabianbormann  Could we move on with this approach for generating doc?

**Comment by luviiit** [comment]
@jinankjain, gn-pages is internally somehow using hydrolysis to extract the docs from the source code and then wrapping it with some pretty html to display all the stuff in pretty manner on a webpage. Now if you want to put these docs in README.md file you have to unwrap it from the html. Instead of doing that just directly use hydrolysis to extract the docs. So effectively we both are on the same path.

The way to generate docs with hydrolysis is as follows:

Put the following in some.html file: (install hydrolysis - npm install hydrolysis)
```
<link rel="import" href="../hydrolysis/hydrolysis.html">

<script>
      var hyd = require('hydrolysis');
      hyd.Analyzer.analyze('/path/to/any-element.html').then(function(analyzer) {
        console.log(analyzer.elementsByTagName['any-element'].desc);
      });
</script>
```
When you open the above html file in the browser, then it would print the docs of `any-element` in the console.

**Comment by jinankjain** [comment]
I just have a one issue that why don't we use gh-pages itself as
documentation. Do we need to put them in readme?

**Comment by luviiit** [comment]
I don't have a very good reason for that but I was trying to follow the way Polymer manages it's elements. For ex. if you look at [carbon-route](https://github.com/PolymerElements/carbon-route) or any other element, it does have docs (without API references) in both readme and a separate web page [here](https://elements.polymer-project.org/elements/carbon-route).

**Comment by jinankjain** [comment]
Ok, if we want to write to the bot itself that convert the json that we receive from using hydrolysis to markdown then writing in js itself would be a good option. 

And one more thing I was going through google group conversation regarding this same thing, I think community itself is going to come with that feature soon. So for the time we could wait and use gh-pages.

**Comment by luviiit** [comment]
Jinank, actually the documentation in the source code is written in such a format that it supports markdown. So when you just extract the docs by the code I mentioned in above comments and just simply put that in readme, it will be displayed in markdown format. For ex. the below docs are directly extracted from gn-map source code using the above code:

The `gn-map` element provides a wrapper for different map types.
If attribute map-type change, the changes will apply to all child elements.
At this time `gn-map` supports `google-map` and `osm-map` and all
children like polygons, points and markers.

Examples:

    <gn-map
      longitude="9.45"
      latitude="38.24"
      zoom="13"
      map-type="GoogleMap">
    </gn-map>

    <gn-map
      longitude="9.45"
      latitude="38.24"
      zoom="13"
      map-type="OpenStreetMap">
    </gn-map>

By default `map-type="GoogleMap"`
